#!/bin/bash
FULL=$(top -l1 | head | grep PhysMem | awk '{print $8}')
FREE=$(top -l1 | head | grep PhysMem | awk '{print $10}')
FREE=${FREE:0:${#FREE}-1}
FULL=${FULL:0:${#FULL}-1}

TOTAL=$(($FREE+$FULL))

RATIO=$(echo "($FULL/$TOTAL)*100"|bc -l)
RATIO=${RATIO:0:2}
echo $RATIO%
