#!/bin/bash
echo $1
if [ $1 == on -o $1 == off ]; then
    networksetup -setairportpower en1 $1
    echo "Wifi turned" $1
else
    b=$1
    b=${b:0:4}
    if [ $b == "name" ]; then
        text=$1
        text=${text:5}
        if [ ${#text} -ge 1 ]; then
            replace="\ "
            text=${text// /$replace}
            replace="\'"
            text=${text//\'/$replace}
            echo $text | xargs networksetup -setcomputername
            echo 'Computer name changed to '$text
        else
            echo 'You must provide a name'
        fi
    else
        echo 'Unknown option: '$b
    fi
fi

