#!/bin/bash
# the name of your primary tmux session
SESSION=$USER
 
# if the session is already running, just attach to it.
tmux has-session -t $SESSION
if [ $? -eq 0 ]; then
    echo "Session $SESSION already exists. Attaching."
    sleep 1
    tmux attach -t $SESSION
    exit 0;
fi
 
# create a new session, named $SESSION, and detach from it
tmux new-session -d -s  $SESSION -n Monitor "sleep 1 &&htop"
# Now populate the session with the windows you use every day
# Some windows I specifically want at a particular index.
 
# 1 - Monitor
tmux select-window -t $SESSION:1 

# Check which interface to monitor

tmux splitw -v -t 1 'sleep 1 &&tail -f /var/log/system.log | cut -c20-'

tmux new-window 'mcabber'
tmux new-window 'rtorrent'

tmux select-pane -L 
tmux attach -t $SESSION
